version: "3.8"
services:
  app:
    image: docker-test-image:development
    container_name: webdevelopmentApp
    volumes:
      - /home/kwong/webdev/BasicWebDevelopment:/usr/src/app
    environment:
      DB_USER: postgres
      DB_HOST: webdevelopmentDB
      DB_NAME: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:alpine
    container_name: webdevelopmentDB
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    container_name: webdevelopmentWeb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - mynetwork

volumes:
  pg_data:

networks:
  mynetwork:
