version: "3.8"
services:
  webdevelopmentApp:
    image: docker-test-image:development
    ports:
      - "8080:3000"
    volumes:
      - /home/kwong/webdev/BasicWebDevelopment:/usr/src/app
    environment:
      DB_USER: postgres
      DB_HOST: webdevelopmentDB
      DB_NAME: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
    depends_on:
      - webdevelopmentDB
    networks:
      - mynetwork

  webdevelopmentDB:
    image: postgres
    container_name: webdevelopmentDB
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5678:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pg_data:

networks:
  mynetwork:
